const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace(/init\(\);\s*$/,'');
const elements=new Map();
const document={addEventListener(){},querySelectorAll(){return []},getElementById(id){if(!elements.has(id))elements.set(id,{value:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){}});return elements.get(id)}};
const context=vm.createContext({document,window:{location:{origin:'http://localhost',pathname:'/'},addEventListener(){}},localStorage:{getItem(){return null}},MutationObserver:class{observe(){}},crypto:require('node:crypto').webcrypto,console,setTimeout,clearTimeout,URL,URLSearchParams});
const run=s=>vm.runInContext(s,context);run(source);
(async()=>{
  run(`db.companies=[{id:'a',name:'A업체'},{id:'b',name:'B업체'}];saveTable=async()=>true;toast=()=>{};
    const receipt=buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-01',material:'패치',qty:'100'});`);
  assert.equal(await run('persistMaterialMove(receipt)'),true);
  await run('persistMaterialMove(receipt)');assert.equal(run('db.material_moves.length'),1);
  run(`const job=buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-02',kind:'작업 완료',material:'패치',work_qty:'15',per_unit:'2',source:'스마트스토어',order_no:'1234'});`);
  await run('persistMaterialMove(job)');
  assert.equal(run('materialBalances()[materialKey(receipt)]'),70);
  assert.equal(run('job.quote_id'),'');assert.equal(run('job.qty'),30);
  assert.equal(run('db.payments.length+db.quotes.length+db.stock_moves.length'),0);
  await assert.rejects(()=>run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('b'),date:'2026-09-03',kind:'작업 완료',material:'패치',work_qty:'1',per_unit:'1'}))`));
  await assert.rejects(()=>run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-03',kind:'반환',material:'패치',qty:'71'}))`));
  await assert.rejects(()=>run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('a'),date:'2026-08-01',kind:'반환',material:'패치',qty:'1'}))`));
  await assert.rejects(()=>run('voidMaterialMove(receipt.id)'));
  run('saveTable=async()=>false');
  assert.equal(await run('voidMaterialMove(job.id)'),false);
  assert.equal(run('materialBalances()[materialKey(receipt)]'),70);
  assert.equal(await run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-03',kind:'반환',material:'패치',qty:'10'}))`),false);
  assert.equal(run('db.material_moves.length'),2);
  run('saveTable=async()=>true');await run('voidMaterialMove(job.id)');
  assert.equal(run('materialBalances()[materialKey(receipt)]'),100);
  assert.equal(run('db.material_moves.length'),2);
  await run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-04',kind:'반환',material:'패치',qty:'10'}))`);
  await run(`persistMaterialMove(buildMaterialMove({...newMaterialDraft('a'),date:'2026-09-05',kind:'불량/분실',material:'패치',qty:'2'}))`);
  assert.equal(run('materialBalances()[materialKey(receipt)]'),88);
  for(const qty of ['-1','0','1.5','abc'])assert.throws(()=>run(`buildMaterialMove({...newMaterialDraft('a'),material:'패치',qty:${JSON.stringify(qty)}})`));
  assert.throws(()=>run(`buildMaterialMove({...newMaterialDraft('a'),material:'패치',qty:'1',date:'2026-02-30'})`));
  assert.ok(run('BACKUP_TABLES.includes("material_moves")&&ERP_TABLES.includes("material_moves")'));
  run('renderMaterials()');assert.ok(elements.get('materialContent').innerHTML.includes('견적서 없이 기록'));
  console.log('PASS: standalone Smart Store work, 2:1 usage, owner isolation, shortage/backdate validation, idempotency, cancellation audit, save failure safety, returns/loss, backup inclusion, render smoke');
})().catch(e=>{console.error(e);process.exitCode=1});
