const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const ctx=vm.createContext({crypto:webcrypto,Date,console,tracksStock:i=>i&&i.type==='단품',localDate:()=> '2026-09-13',stockKeyOf:m=>[m.item_id,m.color,m.spec].join('|')});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../stock-entry.js'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`const items=[{id:'i',type:'단품'}],entry={item_id:'i',color:'WH',spec:'L',date:'2026-09-13',kind:'입고',qty:10,memo:''};const moves=[{...entry,id:'one'}];`);
assert.equal(run(`stockPlan(moves,{kind:'add',entries:[{...entry,qty:3}]},items).impacts[0].after`),13);
run(`const edited=stockPlan(moves,{kind:'edit',id:'one',entries:[{...entry,qty:7}],reason:'오입력'},items);`);
assert.equal(run('edited.impacts[0].after'),7);
assert.equal(run('edited.next.length'),3);
assert.equal(run('moves[0].cancelled_at'),undefined,'planning never mutates source');
assert.equal(run('edited.next[0].qty'),10,'original quantity retained');
assert.equal(run('edited.next[1].reversal_of'),'one');
assert.throws(()=>run(`stockPlan(edited.next,{kind:'void',id:'one',entries:[],reason:'중복'},items)`));
assert.throws(()=>run(`stockPlan(moves,{kind:'void',id:'one',entries:[],reason:''},items)`));
assert.throws(()=>run(`stockPlan([{...moves[0],quote_id:'q'}],{kind:'void',id:'one',entries:[],reason:'x'},items)`));
assert.throws(()=>run(`stockPlan(moves,{kind:'add',entries:[{...entry,kind:'출고',qty:11}]},items)`));
assert.throws(()=>run(`stockPlan(moves,{kind:'edit',id:'one',entries:[{...entry,spec:'S'}],reason:'x'},items)`));
assert.equal(run(`stockPlan(moves,{kind:'void',id:'one',entries:[],reason:'중복'},items).impacts[0].after`),0);
assert.throws(()=>run(`stockStrictQty('1e3')`));assert.throws(()=>run(`stockStrictQty('-1')`));assert.throws(()=>run(`stockStrictQty('0')`));
run(`const multi=stockPlan([],{kind:'add',entries:[entry,{...entry,spec:'S',qty:4}]},items);`);
assert.equal(run('multi.impacts.length'),2);
ctx.needToken=async()=> 'test';ctx.DATA_DIR='/test';ctx.dbxArg=JSON.stringify;ctx.Table={load:async()=>[]};
(async()=>{
 let uploads=0;
 ctx.fetch=async(url,options)=>{if(url.endsWith('download'))return {ok:true,text:async()=>JSON.stringify(run('moves')),headers:{get:()=>JSON.stringify({rev:'r1'})}};uploads++;assert.deepEqual(JSON.parse(options.headers['Dropbox-API-Arg']).mode,{'.tag':'update',update:'r1'});return {ok:true};};
 await run(`saveStockChecked(stockFingerprint(moves),edited.next)`);assert.equal(uploads,1);
 await assert.rejects(run(`saveStockChecked('stale',edited.next)`),/다른 변경/);assert.equal(uploads,1);
 ctx.fetch=async(url)=>url.endsWith('download')?{ok:true,text:async()=>JSON.stringify(run('moves')),headers:{get:()=>JSON.stringify({rev:'r1'})}}:{ok:false,status:409};
 await assert.rejects(run(`saveStockChecked(stockFingerprint(moves),edited.next)`),/동시에/);
 assert.equal(run('moves.length'),1,'failed save preserves source');
 const els=new Map();ctx.document={getElementById(id){if(!els.has(id))els.set(id,{value:'draft',checked:true,disabled:false,close(){},remove(){}});return els.get(id)},querySelectorAll(){return []},querySelector(){return {hidden:false}}};
 ctx.renderStock=()=>{};ctx.toast=()=>{};
 run(`const realRefresh=refreshStockReview;refreshStockReview=()=>{};db={stock_moves:moves,items};stockReview={kind:'add',entries:[entry],fingerprint:stockFingerprint(moves),itemFingerprint:JSON.stringify(items)};saveStockChecked=async()=>{throw Error('offline')};`);
 await run('commitStockReview()');assert.equal(run('db.stock_moves.length'),1);assert.equal(ctx.document.getElementById('ivQty').value,'draft');assert.equal(ctx.document.getElementById('stockReviewCheck').checked,false);
 let finish,calls=0;ctx.testSave=()=>{calls++;return new Promise(resolve=>finish=resolve)};
 run(`saveStockChecked=testSave;`);ctx.document.getElementById('stockReviewCommit').disabled=false;
 const pending=run('commitStockReview()');await run('commitStockReview()');assert.equal(calls,1,'duplicate confirmation blocked');finish();await pending;
 assert.equal(run('db.stock_moves.length'),2);assert.equal(ctx.document.getElementById('ivQty').value,'');
 console.log('PASS: batch, correction reversal, cancellation, reason, linked-record protection, negative stock, strict quantity, revision conflict and source preservation');
})().catch(e=>{console.error(e);process.exitCode=1});
