import test from 'node:test';import assert from 'node:assert/strict';
import {keys,datasetPath,GoogleDriveProvider,DropboxProvider,dropboxIdentity,createStorageRepository,createTable,onboardingReadProvider} from './storage.mjs';
import {emptyData,bootstrap} from '../personal-cloud-onboarding/core.mjs';
import {createGoogleBackend} from '../personal-cloud-onboarding/google-backend.mjs';
function fixture(){const data=emptyData();let revision='1';return {data,setRevision:v=>revision=v,connect:async()=>{},disconnect:async()=>{},list:async()=>keys.map(datasetPath),load:async p=>structuredClone(data[keys.find(k=>datasetPath(k)===p)]),identity:async p=>({provider:'drive',logicalKey:keys.find(k=>datasetPath(k)===p),fileId:p,path:p,revision,revisionKind:'drive.version'})};}
test('seven datasets enter existing Table contract, cloned and schema3',async()=>{const b=fixture(),r=createStorageRepository(new GoogleDriveProvider(b)),t=createTable(r);await r.loadAll();assert.deepEqual(t.load('companies'),[]);assert.equal(t.loadObj('settings').schema,3);t.load('companies').push({});assert.equal(t.load('companies').length,0);assert.equal(r.identities().length,7);});
test('existing workspace performs one discovery; data read concurrency bounded at 3',async()=>{const b=fixture();let lists=0,active=0,peak=0;const list=b.list,load=b.load;b.list=async()=>{lists++;return list();};b.load=async p=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,5));const d=await load(p);active--;return d;};let timing;const p=onboardingReadProvider(new GoogleDriveProvider(b),(_r,t)=>{timing=t;},{initializeNew:true});assert.deepEqual(await bootstrap(p),emptyData());assert.equal(lists,1);assert.equal(peak,3);assert.ok(timing.readMs>=0);});
test('parallel reader drains in-flight calls and does not start remaining work after failure',async()=>{const {parallelRead}=await import('../personal-cloud-onboarding/core.mjs');let active=0,calls=0;await assert.rejects(parallelRead([0,1,2,3,4,5],async n=>{calls++;active++;try{if(n===0)throw Error('synthetic');await new Promise(r=>setTimeout(r,5));}finally{active--;}}),/synthetic/);assert.equal(active,0);assert.ok(calls<=3);});
test('all write entry points deny before backend',async()=>{const p=new GoogleDriveProvider(fixture()),r=createStorageRepository(p),t=createTable(r);for(const fn of [()=>p.create(),()=>p.update(),()=>p.delete(),()=>p.saveSnapshot(),()=>r.saveSnapshot(),()=>r.saveTable(),()=>t.save()])assert.throws(fn,{code:'WRITE_BLOCKED'});});
test('missing/duplicate dataset fail closed without bootstrap',async()=>{for(const paths of [[],keys.slice(1).map(datasetPath),keys.map(()=>datasetPath('companies'))]){const b=fixture();b.list=async()=>paths;const p=onboardingReadProvider(new GoogleDriveProvider(b));await assert.rejects(bootstrap(p),{code:'STORAGE_CONFLICT'});}});
test('onboarding reuses read-only repository, never creation branch',async()=>{const b=fixture(),p=onboardingReadProvider(new GoogleDriveProvider(b));assert.deepEqual(await bootstrap(p),emptyData());assert.throws(()=>p.save(),{code:'WRITE_BLOCKED'});assert.throws(()=>p.prepareFolders(),{code:'WRITE_BLOCKED'});});
test('revision change during load rejects entire draft',async()=>{const b=fixture();const load=b.load;b.load=async p=>{const result=await load(p);b.setRevision('2');return result;};const r=createStorageRepository(new GoogleDriveProvider(b));await assert.rejects(r.loadAll(),{code:'STORAGE_CONFLICT'});assert.throws(()=>r.loadCollection('companies'));});
test('malformed schema and arrays reject',async()=>{for(const mutation of [d=>d.settings.schema=2,d=>d.items={}]){const b=fixture();mutation(b.data);await assert.rejects(createStorageRepository(new GoogleDriveProvider(b)).loadAll(),{code:'STORAGE_INVALID'});}});
test('dispose prevents late snapshot and clears data',async()=>{const b=fixture(),r=createStorageRepository(new GoogleDriveProvider(b));const pending=r.loadAll();r.dispose();await assert.rejects(pending,{code:'CANCELLED'});assert.throws(()=>r.identities());});
test('reconnect discovers the same identities without creation',async()=>{const b=fixture();const first=createStorageRepository(new GoogleDriveProvider(b));await first.loadAll();const ids=first.identities();first.dispose();const second=createStorageRepository(new GoogleDriveProvider(b));await second.loadAll();assert.deepEqual(second.identities(),ids);});
test('Dropbox App Folder identity boundary, same schema, no legacy lookup',async()=>{const b=fixture();b.identity=async p=>dropboxIdentity(keys.find(k=>datasetPath(k)===p),{'.tag':'file',id:'synthetic-id:'+p,rev:'synthetic-rev',path_lower:('/'+p).toLowerCase()});assert.deepEqual(await createStorageRepository(new DropboxProvider(b)).loadAll(),emptyData());assert.throws(()=>dropboxIdentity('companies',{'.tag':'file',id:'id:x',rev:'1',path_lower:'/erp/companies.json'}),{code:'STORAGE_CONFLICT'});});
test('Google readOnly transport blocks POST even if bootstrap attempted',async()=>{let posts=0;const b=createGoogleBackend({readOnly:true,oauth:{authorize:async()=>({accessToken:'synthetic',expiresAt:Date.now()+60000}),close(){}},locks:{request:async(_n,_o,fn)=>fn({})},fetcher:async(_url,options)=>{if(options.method!=='GET')posts++;return new Response(JSON.stringify({files:[],ids:Array.from({length:15},(_,i)=>'synthetic-'+i)}));}});await b.connect();await assert.rejects(b.prepareFolders((await import('../personal-cloud-onboarding/core.mjs')).folders),{code:'WRITE_BLOCKED'});assert.equal(posts,0);assert.equal(b.metrics().datasetCreateRequests,0);await b.disconnect();});
test('Google metadata/list/media contract: 7 identities, 10 GETs, reconnect same IDs',async()=>{
 const {folders}=await import('../personal-cloud-onboarding/core.mjs');
 const paths=[...folders,...keys.map(datasetPath)],nodes=paths.map((path,i)=>({id:'synthetic-'+i,name:path.split('/').pop(),mimeType:folders.includes(path)?'application/vnd.google-apps.folder':'application/json',appProperties:{naroPersonalCloud:'1'},parents:[path.includes('/')?'synthetic-'+paths.indexOf(path.slice(0,path.lastIndexOf('/'))):'root'],version:'1',trashed:false}));
 const methods=[];const fetcher=async(url,options)=>{
  methods.push(options.method);const u=new URL(url);let body;
  if(u.pathname.endsWith('/files')){const q=u.searchParams.get('q');body={files:nodes.filter(n=>(!q.includes(' in parents')||q.includes("'"+n.parents[0]+"' in parents"))&&q.includes("name = '"+n.name+"'")&&!n.trashed)};}
  else {const node=nodes.find(n=>u.pathname.endsWith('/'+n.id));assert.ok(node);body=u.searchParams.get('alt')==='media'?(node.name==='settings.json'?{schema:3}:[]):node;}
  return new Response(JSON.stringify(body));
 };
 const sessions=[];
 for(let i=0;i<2;i++){
  const backend=createGoogleBackend({readOnly:true,fetcher,oauth:{authorize:async()=>({accessToken:'synthetic',expiresAt:Date.now()+60000}),close(){}}});
  const provider=new GoogleDriveProvider(backend);await provider.connect();const repository=createStorageRepository(provider);
  assert.deepEqual(await repository.loadAll(),emptyData());sessions.push(repository.identities());assert.equal(backend.metrics().readRequests,10);assert.equal(backend.metrics().datasetCreateRequests,0);await provider.disconnect();
 }
 assert.deepEqual(sessions[0],sessions[1]);assert.ok(methods.every(m=>m==='GET'));
});
